name: delete-workflow-run-logs
on:
  schedule:
    - cron: '30 22 * * 3'
  workflow_dispatch:

jobs:
  delete-logs:
    runs-on: ubuntu-latest
    steps:
      - name: delete-workflow-run-logs
        uses: dext7r/deleteWorkflowRunLogs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          per_page: 100
          expire_time: 7d
          status: completed
          repo: ${{ github.repository.repo }}
          owner: ${{ github.repository.owner }}
  commit-comment:
    runs-on: ubuntu-latest
    steps:
      - name: commit-comment
        uses: dext7r/commit-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This commit was made with the following details:
            - Commit ID: ${{ github.sha }}
            - Commit Message: ${{ github.event.head_commit.message }}
            - Run_id: ${{ github.run_id }}
            - Repository: ${{ github.repository }}
            - Commit Time: ${{ github.event.head_commit.timestamp }}
            - Commit Author: ${{ github.event.head_commit.author.name }}
            - Commit Author Email: ${{ github.event.head_commit.author.email }}
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: push-notifications
        uses: dext7r/pushNotifications@main
        with:
          TYPE: Qmsg
          TITLE: push-notifications action
          DESP: |
            seekjob action is running
          QMSG_KEY: ${{ secrets.QMSG_KEY }}
          QMSG_QQ: ${{ secrets.QMSG_QQ }}
          QMSG_PUSH_TYPE: send
